### PR TITLE
Fancier readme

### PR DESCRIPTION
**Pull request by aha999**
Hey. Congrats on your first open source app! i made your readme a bit fancier. I hope you like it so far.

### CODE REVIEW

**Review by RushikeshKamewar — APPROVED** [review]
Looks good 👍

**Comment by RushikeshKamewar** [comment]
I was not sure how to do this and was too lazy to learn this 😅. Thanks for helping me out.

**Comment by RushikeshKamewar** [comment]
Hi, I'm not sure how to get in contact with you. I'm working on a new project, I might need some help again for the README if you are available 😅

**Comment by aha999** [comment]
@RushikeshKamewar sure, i can help if i can :) you can contact me on email [9a9h9a@gmail.com](mailto:9a9h9a@gmail.com) or on Linkedin profile, linked on my profile.

**Pull request merged**
